[manifest]
version = "1.0.0"
dump_lua = true
priority = -1

[[patches]]
[patches.pattern]
target = "engine/ui.lua"
pattern = '''if self.UIT == G.UIT.T then self:update_text() end'''
position = "after"
payload = '''
if _G.MYRIAD_INTERNAL_IF_YOU_USE_THIS_YOU_ARE_FIRED.hideNumbers and self.UIT == G.UIT.T then
	self.config.text_drawable:set(tostring(self.config.text):gsub("%d[0-9,.]+%d", "???"):gsub("%d", "?"))
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "engine/text.lua"
pattern = '''local current_letter = 1'''
position = "after"
payload = '''
if _G.MYRIAD_INTERNAL_IF_YOU_USE_THIS_YOU_ARE_FIRED.hideNumbers then v = v:gsub("%d[0-9,.]+%d", "???"):gsub("%d", "?") end
'''
match_indent = true
